### ISSUE TITLE
Sample code in README not working

### ISSUE THREAD

**Issue by mikialex** [qmuntal/gltf#1]
I'm just try to use this project but sample code in readme.md not works. I'm new to golang and gltf.  maybe demo code should be this? :

```
	doc := &gltf.Document{
		Scene: 0, 
		Asset: gltf.Asset{Generator: "qmuntal/gltf"}, 
		Scenes: []gltf.Scene{
			{
				Extras: 8.0, Extensions: gltf.Extensions{"a": "b"}, Name: "s_1",
			},
		},
	}
	if err := gltf.Save(doc, "./a.gltf", false); err != nil {
		panic(err)
	}
```

**Comment by qmuntal** [comment]
You are right @mikialex, tanks! 

I've just fixed the missing package scope in https://github.com/qmuntal/gltf/commit/7fc6bd8d61f22044cc57500943265feb257ee3c7
