### ISSUE TITLE
API surface that doesn't require knowledge of glTF to use

### ISSUE THREAD

**Issue by naikrovek** [qmuntal/gltf#15]
I would like to see an API that lets someone supply a list of vertices, zero or more material definitions, and one or more lists of vertex indices to define triangles, each with an associated material reference, and have all the nuts and bolts of assembling the buffer, bufferviews, and accessors done automatically.  Simply calling .Save on that type should allow the user to then persist this model to disk.

I don't know if that is within the scope of this library, and I felt it needed suggesting, in case it is.

**Comment by naikrovek** [comment]
oh, I should add that I am only hoping for a simple API so that users who have vertex and triangle data are able to easily convert to glTF, and I am not asking for a complete API supporting all features of glTF.

**Comment by qmuntal** [comment]
I like the proposal! It makes sense to add some helpers in the most used components to help builing them without having to go through all the glTF spec. I'll see how it can be done without adding more complexity to the API. 
Feel free to add any sugestion.

**Comment by naikrovek** [comment]
Suggestions... Well, I am not imaginative, so I was just thinking that there would be some raw Vertex, Triangle, Material, and maybe Mesh types in this library, solely for this type of use case, and a user would leverage those input-only types to just wrap those primitives types into a valid glTF file.

**Comment by qmuntal** [comment]
I've been working on this issue for a while in the [modeler](https://github.com/qmuntal/gltf/tree/modeler) branch. 
Until now I have implement what I think to be a great way to manage raw buffers inside the `binary` package. It is still low level functionality, but a step closer to having a friendly API.

**Comment by naikrovek** [comment]
Excellent, thank you!

**Comment by qmuntal** [comment]
The version v0.13.0 has a brand new modeler package, which contains useful methods to create complex geometries without much burden by assembling buffer, bufferviews, and accessors automatically. I even added a loseless compression algorithm that can reduce up to 10% the size of the gltf!

There still room for improvement in the Scene and Mesh handling, but I think that this issue is pretty much done.
