### ISSUE TITLE
Modeler.AddImage() seems to break buffer.ByteLength

### ISSUE THREAD

**Issue by binzume** [qmuntal/gltf#22]
I tried to embed the texture image into .glb using gltf.Modeler but generated a broken file.

in modeler.go
```
	buffer.ByteLength += uint32(len(buffer.Data))
```
I think, `=` should be correct, not `+=`.

**Comment by qmuntal** [comment]
Thanks for spoting this bug. You assumtion seems to be right. I've fixed it in branch `fix-add-image`, plus added some tests. Can you try using this branch to see if it completly fix your issue?

**Comment by binzume** [comment]
Thanks for the quick response. My issue was solved with your fix!

**Comment by qmuntal** [comment]
Fixed in v0.14.1.
