### ISSUE TITLE
Referenced buffer been overwrite

### ISSUE THREAD

**Issue by mikialex** [qmuntal/gltf#3]
I am using your project to create gltf file.  I have draco precompressed geometry data like a.drc, and I referenced it in a buffer in document. When I save the document, the a.drc file will be overwrite. It size becomes zero.  

This is how I define my buffer

``` go
buffer := gltf.Buffer{
		URI:       "a.drc",
		ByteLength:  123,
	}
```

This is how I save the doc

``` go
if err := gltf.Save(doc, path, false); err != nil {
	panic(err)
}
```

**Comment by qmuntal** [comment]
The usw case of saving a buffer that is not completly loaded into memory is not taken into account yet, I'll investigate it during this week. As workarround you can load the draco in the memory sloce of the buffer and save it as you are doing now, I think it should work.

**Comment by qmuntal** [comment]
In v0.8.1 if added #7, which prevent to flush buffer data if the `buffer.Data` length is 0.

**Comment by mikialex** [comment]
yes, It works.  thanks
