### ISSUE TITLE
how to use modeler.WriteIndices

### ISSUE THREAD

**Issue by tawfik741** [qmuntal/gltf#30]
Hi qmuntal , 
I'm pretty new to this low level  of  glTF editing ,
I spent two  days trying to make find the right parameters for the modeler's writeIndices 
All i'm trying to  do now is write a simple triangle :
```
package main

import (
    "github.com/qmuntal/gltf"
    "github.com/qmuntal/gltf/modeler"
)

func drawTriangle() {
    doc := gltf.NewDocument()
    
    positionAccessor := modeler.WritePosition(doc, [][3]float32{{0, 0, 0}, {0, 10, 0}, {0, 0, 10}})
    indicesAccessor := modeler.WriteIndices(doc, []uint8{   0, 1, 0, 
                                                            0, 0, 1, 
                                                            0, 0, 1 })
    colorIndices := modeler.WriteColor(doc, [][3]uint8{{50, 155, 255}, {0, 100, 200}, {255, 155, 50}})
    
    doc.Meshes = []*gltf.Mesh{{
        Name: "Pyramid",
        Primitives: []*gltf.Primitive{{
            Indices: gltf.Index(indicesAccessor),
            Attributes: map[string]uint32{
              "POSITION": positionAccessor,
              "COLOR_0":  colorIndices,
            },
        }},
    }}
    doc.Nodes = []*gltf.Node{{Name: "Root", Mesh: gltf.Index(0)}}
    doc.Scenes[0].Nodes = append(doc.Scenes[0].Nodes, 0)
    if err := gltf.SaveBinary(doc, "./example.glb"); err != nil {
        panic(err)
    }
}
func main (){
    drawTriangle()
}
``` 
I tried two of the examples in the repo (the second one on the md file and example_test.go ) but they didn't work . 
the pyramid one on the md file is working fine and this code is trying to replicate your example but i don't know the data that i'm supposed to pass as indices . i tried 

- Normals : passing 1,0,0,1,0,0,1,0,0
 

Thanks for these contributions . Lots of respect for your code .

**Comment by qmuntal** [comment]
Hi @tawfik741. Looking into your code I saw that I was not writing the `byteStride` for vertex attributes which require padding to achieve the 4 byte alignment. It is fixed in v0.17.2.

Going back to your question, the indices slice must contain 3 integers for each triangle in the mesh, which reference vertex in the position accessor. Therefore if you want to write just one triangle you need to use this: `indicesAccessor := modeler.WriteIndices(doc, []uint8{0, 1, 2})`.

You can find many tutorials and guides of how to construct this type of meshes, just search for ´indexed mesh´.

**Comment by tawfik741** [comment]
Hey @qmuntal  ,
Thanks a lot for your help . I managed to make the code work for the triangle .
I really like that modeler feature . Nice design .
I then managed to update to v0.17.2 after finding the 4 byte alignment problem . Unfortunately , when doing so , the modeler gives a corrupted output . when i load the output file to babylonjs sandbox i get `Length in header does not match actual data length: 2476 != 1268 .` .
I'll dig deeper now . I find your project awesome . I hope I'll be able to commit some code to it .

**Comment by qmuntal** [comment]
Thanks for these nice words, I've invested many ours in designing a friendly API, even though it still have some room for improvement.

About the corrupted input, can you share a code snippet that reproduces it? Also, can you reproduce the issue with v0.17.1?

**Comment by tawfik741** [comment]
Yes sure , 
here is my code for both `v0.17.1` and `v0.17.2` :
```
package main

import (
    "github.com/qmuntal/gltf"
    "github.com/qmuntal/gltf/modeler"
    
)

func drawRectangle() {
    doc := gltf.NewDocument()
    
    positionAccessor := modeler.WritePosition(doc, [][3]float32{{0, 0, 0}, {0, 10, 0}, 
                                                                {0, 0, 10},{0, 10, 10}})
    
    indicesAccessor := modeler.WriteIndices(doc, []uint8{   0, 1, 2 , 
                                                            3, 2, 1})
    colorIndices := modeler.WriteColor(doc, [][3]uint8{{50, 155, 255}, {0, 100, 200}, {255, 155, 50}})
    
    doc.Meshes = []*gltf.Mesh{{
        Name: "drawTriangle",
        Primitives: []*gltf.Primitive{{
            Indices: gltf.Index(indicesAccessor),
            Attributes: map[string]uint32{
              "POSITION": positionAccessor,
              "COLOR_0":  colorIndices,
            },
        }},
    }}
    doc.Nodes = []*gltf.Node{{Name: "Root", Mesh: gltf.Index(0)}}
    doc.Scenes[0].Nodes = append(doc.Scenes[0].Nodes, 0)
    if err := gltf.SaveBinary(doc, "./example.glb"); err != nil {
        panic(err)
    }
}
func main (){
    drawRectangle()
}
```
Here is the glb exports with `v0.17.1` and `v0.17.2` : [google drive link](https://drive.google.com/drive/folders/1Gc8cdYJGcAbtceUapefyAN9_JmUDDvEQ?usp=sharing)

**Comment by qmuntal** [comment]
All accessors of the same primitive must have the same count but your COLOR_0 attribute has 3 elements and the POSITION has 4 elements. If you add one more color then the resulting glb will be accepted by Babylon.js.

This makes me think that I should add some validations to the save process...

**Comment by tawfik741** [comment]
my bad , this works perfectly now , 
I'll add primitives to your modeler and I'm interested in helping for the validation 
Is there a slack i can join for development ?

**Comment by qmuntal** [comment]
> I'll add primitives to your modeler and I'm interested in helping for the validation
Is there a slack i can join for development ?

There is no slack channel for this repo and at the moment I don't plan to set up one, but PRs are more than welcome and I will review them even if they are WIP.
