### ISSUE TITLE
Is there enough ensurePadding?

### ISSUE THREAD

**Issue by aoisensi** [qmuntal/gltf#32]
Hello. I'm new at gltf.

https://github.com/qmuntal/gltf/blob/6f371950e7fa5384366436658da419b8f27ee3ce/modeler/write.go

I read the code.
I think almost every `modeler`'s `Write*` method needs to have `ensurePadding`.
The lack of it produces poor results in my converter.
Thanks for reading.
Sorry for bad English.

**Comment by qmuntal** [comment]
Hi @aoisensi, thanks for reporting your issue.

The only `Write*` methods that don´t have `ensurePadding` are `WriteImage` and `WriteBufferView`. Are you using refering to any of those two functions?

Also, could you share some lines of code to reproduce your issue?

**Comment by aoisensi** [comment]
Thank you for quick response.
First, that was my bad!
I tried write position with WriteBufferView.
And maybe, my browser was broken. (Ctrl+F `ensurePadding` was only 2 results.)
I’m using `WritePosition` now and solved.
I'm sorry to build the useless issue.
And thank you for writing beautiful library!
