### ISSUE TITLE
Why limit everything in the modeler to 32 bits 

### ISSUE THREAD

**Issue by tawfik741** [qmuntal/gltf#33]
I was wondering why the modeler has a limit of 32 bits for indices and positions

**Comment by qmuntal** [comment]
The `modeler` supports all the combination of accessor / component types defined in the core spec ([link](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes)). If you are using any extension that allows other combinations then it is not difficult to implement your own wrapper on top of `ReadAccessor`  and `WriteAccessor`.

Additionally, the core spec, and in fact most rendering devices support up to 32 bit numbers.

**Comment by tawfik741** [comment]
thank you
