### ISSUE TITLE
Sampler's MagFilter, MinFilter, WrapS and WrapT won't be included in encoded JSON

### ISSUE THREAD

**Issue by thara** [qmuntal/gltf#36]
When Sampler's MagFilter, MinFilter, WrapS and WrapT fields are zero values, they won't be included in encoded JSON document.
These fields' types have MarshalJSON implemented, but IIUC omitempty is evaluated **before** MarshalJSON and the values are omitted (because they're zero), so the encoded JSON won't have them.
I think that there are 2 options for resolving this issue.

- A. Remove omitempty tag from MagFilter, MinFilter, WrapS and WrapT fields
- B. Ignore first value by assigning to blank identifier before MagLinear, MinLinear, WrapRepeat

What do you think?
I'll try to make a PR after you decide.

**Comment by qmuntal** [comment]
Thanks for rising this issue @thara.

Checking the glTF spec I see that `magFilter` and `minFilter` does not define any default value, and is up to the runtime to decide which method to use. Therefore, as mentioned in this issue, when the `magFilter` and/or `minFilter` as set they must also appear in the JSON. To properly solve this issue the the types `MagFilter` and `MinFilter` should be modified so their zero value are not `MagLinear` and `MinLinear` but two newly defined constants: `MagUndefined` and `MinUndefined`. This way the user would be able to detected an undefined filter scenario.

On the other hand `WrapS` and `WrapT` do have a default value (`10497`)  which corresponds to the zero value of `WrappingMode`, so it should be find to omit these fields in the zero-case.

@thara do you agree with my reasoning? If so a PR will be more than welcome!

**Comment by qmuntal** [comment]
Almost right, the default value of `WrapS` and `WrapT` is already `10497`, aka `WrapRepeat`, so I don't see any issue with these properties.

See https://github.com/qmuntal/gltf/blob/master/const.go#L342.

**Comment by thara** [comment]
This might just be my idea but if `WrapS` or `WrapT` is `WrapRepeat`(zero value),  `json.Marshal` looks at `omitempty` at the first and don't call `MarshalJSON`.

For your reference, https://play.golang.org/p/4wTEN3VyZo7

**Comment by qmuntal** [comment]
Your interpretation is the correct one. My point is that the gltf spec says that `wrapS` and `wrapT` are not required **and** if not specified the default value is `10497`, therefore there is no need to include these properties in the JSON if their value is `WrapRepeat`, and the design decision of this library is to omit all properties which are not defined and its value is the default value.
