### ISSUE TITLE
GLTF save errors with invalid buffer

### ISSUE THREAD

**Issue by xackery** [qmuntal/gltf#49]
https://github.com/qmuntal/gltf/blob/58807b50227bd15975e015ce2c4242efa3db9568/example_test.go#L17

If you change last line to:
```go
 if err := gltf.Save(doc, "./example.gltf"); err != nil {
		panic(err)
	}
```
You get 
```
panic: gltf: Invalid buffer.uri value '' [recovered]
	panic: gltf: Invalid buffer.uri value ''
```

seems glb and gltf aren't treated same? any tips to resolve the above?

**Comment by qmuntal** [comment]
Can you check if you are facing the same problem as in #45?

**Comment by xackery** [comment]
> Can you check if you are facing the same problem as in #45?

Yep, adding:
```go
for _, buff := range doc.Buffers {
		buff.EmbeddedResource()
	}
```
fixed it. It may be worthwhile adding this to the README as a note, it isn't obvious. 
Thanks!
