### ISSUE TITLE
Incorrect behaviour when loading files containing spaces

### ISSUE THREAD

**Issue by ptxmac** [qmuntal/gltf#60]
Take a look at the glTF sample files called [Box With Spaces](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box%20With%20Spaces/glTF/Box%20With%20Spaces.gltf#L151)

This file has a `uri` reference to `Box With Spaces.bin`. But this library performs urlencode of the URI so spaces become `%20` and then fails because it cannot find a file named `Box%20With%20Spaces.bin`

The url-encoding happens because of a round-trip through `net/url.Parse`

A solution would be to only use the parsed URL if the scheme is not empty. i.e. the URL is http/file/etc

**Comment by qmuntal** [comment]
Thanks for reporting this issue. I'll submit following the recommendations laid out in https://github.com/KhronosGroup/glTF/issues/1449.
