### ISSUE TITLE
Allow removal of unused data

### ISSUE THREAD

**Issue by anierzad** [qmuntal/gltf#65]
Hello, firstly thank you for building this module; it's been really useful in a project I've been playing with.

My apologies if there is something in the documentation I've overlooked but I can't find a way to remove data that is no longer used.

For example in my use case, I'm loading a source gltf file, making some modifications to some of the data using the `modeler` package such as reading, editing and then writing vertex positions as well as replacing a texture assigned to a material). I'd like to be able to remove the old, no longer referenced, vertex and image data to keep the resulting file size as small as possible.

I'd love to contribute to the project too so if there's any way I could help with the implementation of the above I'd be more than happy to. However I am very new to gltf, I've only known about the formats existence for a few weeks.

**Comment by qmuntal** [comment]
Hi @anierzad, thanks for submitting this request. I'll think about this during the weekend and report back.
