### ISSUE TITLE
Typo in lightspuntual package name

### ISSUE THREAD

**Issue by mokiat** [qmuntal/gltf#66]
This one is a bit of a nit picking but I assume the `lightspuntual` package was intended to be `lightspunctual` (a `c` is missing)?

**Comment by qmuntal** [comment]
That's an unfortunate typo.  Thanks for reporting, I'll correct it if this package evers gets to `v1.0` (which I plan to do when/if Go ever gets union types).

**Comment by mokiat** [comment]
Hi! No problem. There are some other small inconsistencies I have come across. I am not sure if you are interested in such corrections. If you are, maybe I can go through the code again and report them all in one single issue?

Otherwise, your library is excellent. I have already successfully used it in my hobby project [Rally-MKA](https://mokiat.itch.io/rally-mka) / ([source code](https://github.com/mokiat/rally-mka)) to convert gltf models into my own internal format. Just using this opportunity to say: many thanks.

As for union types - yes, it's unfortunate that Go doesn't have them yet. There are situations where it can really be useful and optimal. Though I am not sure if they are even on the agenda.

**Comment by qmuntal** [comment]
>  I am not sure if you are interested in such corrections. If you are, maybe I can go through the code again and report them all in one single issue?

I'm definitely interested in all typos and glitches you know about. Please report them in a single issue. If there are enough I may cut a new version with them fixed.

**Comment by mokiat** [comment]
Thanks for fixing this :partying_face: 

I still have on my TODO to collect potential improvements for a future release. It is just that I have not gotten yet to redoing my model loading code which would best help me identify them. I am hopeful that soon I will get to it :crossed_fingers:

**Comment by mokiat** [comment]
I now had a closer look at the change and while the package name has been changed, the folder name remains with a typo. Should it maybe be changed as well? It is already a breaking change either way.
