### ISSUE TITLE
Restriction on buffer.uri containing ".." is too limiting

### ISSUE THREAD

**Issue by Mythic117** [qmuntal/gltf#74]
![image](https://github.com/qmuntal/gltf/assets/17878098/1f99f1fd-c502-4156-8dcd-7a77c015a277)

Perhaps this restriction is intended to prevent navigation to the parent directory. However, a buffer with ".." in its base name cannot be loaded either, for example, "A..B.bin".

**Comment by qmuntal** [comment]
Thanks for reporting this issue @Mythic117. Agree that this is too strict. We could use [filepath.IsLocal](https://pkg.go.dev/path/filepath#IsLocal) instead here.
