### ISSUE TITLE
Animation channel's Sampler should be required

### ISSUE THREAD

**Issue by mokiat** [qmuntal/gltf#80]
According to the spec, the `sampler` field in the `channel` struct should be required but in the library it is not.

Spec: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-animation-channel
Lib: https://github.com/qmuntal/gltf/blob/887e847fa6c77ba802f74c546a9171e688536a8e/gltf.go#L446

**Comment by qmuntal** [comment]
Thanks! Will fix in next release.
