### ISSUE TITLE
Can I write `inverseBindMatrices` with `modeler`?

### ISSUE THREAD

**Issue by aoisensi** [qmuntal/gltf#91]
It is `[][16]float32`.

**Comment by qmuntal** [comment]
You can write it using `modeler.WriteAccessor`:

```go
modeler.WriteAccessor(doc, gltf.TargetArrayBuffer, data)
```

Note that data must be `[][4][4]float32`, not `[][16]float32`.

I've added a helper to read/write inverseBindMatrices in #92.

**Comment by aoisensi** [comment]
Thank you! <3

**Comment by aoisensi** [comment]
I'm not completely sure, but it seems that you can't specify a `target` for `inverseBindMatrix`.
glTF-Validator says there is an error.
